version: 2
jobs:
  build:
    environment:
      CC_TEST_REPORTER_ID: 907c5ca1f77a9f4d4ab5a7ff8e9d2d616abaf8c373f2d2ddb9a652d5ad985642

    docker:
      - image: circleci/golang:latest

    steps:
      - checkout

      - restore_cache:
        keys:
          - v1-pkg-cache

      - run:
        name: Install test coverage tool
        command: |
          go get -v github.com/codeclimate/test-reporter

      - run:
        name: Run unit tests
        command: |
          test-reporter before-build
          go test -covermode atomic -coverprofile c.out ./...
          test-reporter after-build # magic..?

      - save-cache:
          key: v1-pkg-cache
          paths:
            - "/go/pkg"
