version: 2
jobs:
  build:
    environment:
      CODECLIMATE_REPO_TOKEN: 907c5ca1f77a9f4d4ab5a7ff8e9d2d616abaf8c373f2d2ddb9a652d5ad985642

    docker:
      - image: circleci/golang:1.11rc2-node

    steps:
      - checkout

      - run:
          name: Print Go version
          command: go version

      - run:
          name: Install test coverage tool
          command: sudo npm install -g codeclimate-test-reporter
            # curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            # chmod +x ./cc-test-reporter

      - run:
          name: Run tests
          command: |
            go build ./...
            go test -race -covermode atomic -coverprofile cover.out ./...
            codeclimate-test-reporter < cover.out
          environment:
            GO111MODULE: "on"
